backend:
  name: git-gateway
media_folder: "/static/uploads"
public_folder: "/uploads"
locale: 'de'
collections:
  - label: "Pages"
    name: "pages"
    format: "yml"
    editor:
      preview: false
    files:
      - label: "Landing Page"
        name: "landing"
        file: "content/landing.md"
        fields:
          - {label: "ID (Nicht ändern!)", name: "id", widget: "number"}
          - {label: "Header Video", name: "header_video", widget: "file"}
          - {label: "Header Thumbnail", name: "header_thumbnail", widget: "file"}
          - {label: "Zitat", name: "cite", widget: "string"}
          - label: "Portraits"
            name: "portraits"
            widget: "list"
            fields:
              - {label: "Photo", name: "photo", widget: "image"}
          - {label: "Intro", name: "intro", widget: "text"}
          - label: "Top Services"
            name: "topServices"
            widget: "list"
            fields:
              - {label: "Cover Picture", name: "cover", widget: "image"}
              - {label: "Titel", name: "title", widget: "string"}
              - {label: "Kurzbeschreibung", name: "description", widget: "text"}
          - label: "Services"
            name: "services"
            widget: "list"
            fields:
              - {label: "Titel", name: "title", widget: "string"}
              - {label: "Kurzbeschreibung", name: "description", widget: "text"}
          - label: "Clients"
            name: "clients"
            widget: "list"
            fields:
              - {label: "Logo", name: "logo", widget: "image"}
          - label: "Referenzen"
            name: "references"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Unternehmen", name: "company", widget: "string"}
              - {label: "Referenztext", name: "reference_text", widget: "text"}
          - {label: "Agentur Header", name: "about_header", widget: "string"}
          - {label: "Agentur Beschreibung", name: "about_description", widget: "text"}
          - {label: "Agentur Foto", name: "about_image", widget: "image"}
          - {label: "Beschreibung Kontaktanfrage", name: "contact_description", widget: "text"}
